version: "3.9"
services:

  # Service Example / Notes
  # ==================
  # name_of_service:                                    # This can be any name you want
  #   build: ./docker/<folder_name_here>                # This is where you would have dockerfile plus any required dlls, jars, files, etc
  #   image: <desired_image_name_here>                  # This is where you can put the desired name of the image for when it gets built
  #   container_name: <desired_container_name_here>     # This is where you can put the desired name of the container for when it gets built
  #   ports:
  #     - "<container_port>:<virtual_port>"             # This is where you can put the desired ports
  #   networks:
  #     - <network_name_here>                           # This is where you can attach this service to a desired network 
  api_gateway:
    build: ./docker/api_gateway
    image: ecommerce-apigateway:1.0
    container_name: api_gateway
    depends_on:
      -eureka
    ports:
      - "80:8888"
    networks:
      - basenetwork

  account_service:
    build: ./docker/account_service
    image: ecommerce-accountservice:1.0
    container_name: account-service
    depends_on:
      - registration_service
      - account_database
    ports:
      - "10000:5009"
    networks:
      - basenetwork

  cart_service:
    build: ./docker/cart_service
    image: ecommerce-cartservice:1.0
    container_name: cart_service
    depends_on:
      - registration_service
    ports:
      - "10001:5278"
    networks:
      - basenetwork
  
  email_service:
    build: ./docker/email_service
    image: ecommerce-emailservice:1.0
    container_name: email-service
    depends_on:
      - registration_service
    ports: 
      - "10002:8080"
    networks:
      - basenetwork

  payment_service:
    build: ./docker/payment_service
    image: ecommerce-payment_service:1.0
    container_name: payment-service
    depends_on:
      - registration_service
    ports:
      - "10003:8080"
    networks:
      - basenetwork

  order_service:
    build: ./docker/order_service
    image: ecommerce-order_service:1.0
    container_name: order-service
    depends_on:
      - registration_service
      - order_database
    ports:
      - "10004:8080"
    networks:
      - basenetwork

  catalog_service:
    build: ./docker/catalog_service
    image: ecommerce-catalog_service:1.0
    container_name: catalog_service
    depends_on:
      - registration_service
      - item_database
    ports:
      - "10005:5130"
    networks:
      - basenetwork

  order_database:
    image: "mongo:latest"
    container_name: order-database
    environment:
      MONGO_INITDB_DATABASE: "OrdersDB"
    ports:
      - "10006:27017"
    networks:
      - basenetwork

  item_database:
    image: "mongo:latest"
    container_name: itemdb
    environment:
      - MONGO_INITDB_DATABASE=ItemDb
    ports: 
      - "10007:27017"
    networks:
      - basenetwork

  account_database:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "abc123!!@"
      ACCEPT_EULA: "Y"
    ports:
      - "10008:1433"
    networks:
      - basenetwork

  registration_service:
    image: "steeltoeoss/eureka-server"
    container_name: "eureka"
    ports:
      - "10009:8761"
    networks:
    - basenetwork
  
networks:
  basenetwork:
    name: "ecommerce"